# permissions for end users to view localpvs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: localpv-viewer-role
rules:
- apiGroups:
  - uhana.vmware.my.domain
  resources:
  - localpvs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - uhana.vmware.my.domain
  resources:
  - localpvs/status
  verbs:
  - get
